name: countdown_flutter
description: A simple countdown plugin for flutter. Provides a simple way to create a countdown in your app.
version: 0.1.3
homepage: https://github.com/Leocardoso94/flutter-countdown

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter: